<table class="table table-striped">
    <thead>
        <tr>
          <th>id</th>
          <th>user</th>
          <th>name</th>
          <th>created</th>
          <th>updated</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->addresses as $address): ?>
            <tr>
              <td><?php echo $address->getId(); ?></td>
              <td><?php echo $address->getUser()->getUsername(); ?></td>
              <td><?php echo $address->getName(); ?></td>
              <td><?php echo $address->getCreated()->format('d-m-Y H:i:s'); ?></td>
              <td><?php echo $address->getUpdated()->format('d-m-Y H:i:s'); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>